version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name h4b-cicd-codedeploy-application --s3-location s3://h4b-cicd-artifact-fujisiroms/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src